spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hu704725075/spring-config.git
          default-label: master
          search-paths: /**
          basedir: target/config
    application:
      name: config-server
server:
  port: 8006